-- =============================================================================
-- 01_maestros.sql -- datos reales y permanentes (es_demo = false)
--
-- Plan: doc 02 §14.
-- Se carga en cada `supabase db reset`, asi que debe ser idempotente.
--
-- Estado en la Fase 0: vacio. El catalogo de roles se mudo a una migracion (ver
-- abajo). El resto de maestros (unidades, categorias, 22 insumos, 6 proveedores,
-- configuracion del sitio, zonas de reparto...) llega en la Fase 2.
--
-- Regla que salio de este tropiezo: si un dato tiene que existir en TODOS los
-- entornos, va en una migracion. Las semillas son para lo que solo necesita el
-- entorno de desarrollo, porque `supabase db push` no las aplica.
-- =============================================================================

-- --- Roles ------------------------------------------------------------------
-- Se mudaron a la migracion 0004_catalogo_roles.sql.
--
-- `supabase db push` no aplica semillas, asi que dejarlos aqui hacia que
-- produccion se quedara sin ellos y que `perfiles.rol` rompiera su clave
-- foranea al crear el primer usuario. No son datos de ejemplo: son la
-- contraparte legible del enum app.rol_usuario, es decir estructura.
